@startuml recovery_diagram
start

repeat :checkout to next Record;

if(isAlive && healthPoints!=100) then(yes)

if(Is in Hospital?) then (yes)
:Recover + Doctor's heal;
else (no)
:Recover;
endif
endif

repeat while(more records?) is (yes) 

stop
@enduml