@startuml beginning diagram 
title Simulation
start
:"Download simulation settings";
:"Creating a map from empty field";
:"Arrangement of objects\non the map";
:"The beginning of the simulation";
repeat
:"Perform movement round";
:"Perform infect round";
:"Perform illness round";
:"Perform recover round";
repeat while("Stop condition met") is (no)
->yes; 
stop
@enduml