@startuml infect_round_07052020

start

repeat :checkout to next record;
  if (is being in this record \ndisease sensitive?) then (yes)
    if (is being in this record \nalive?) then (yes)
        if (is there any disease?) then (yes)
            repeat :checkout to next disease;
                repeat :checkout to next \nneighbouring field;
                    if (is this neighbour disease sensitive?) then (yes)
                        :infect neighbour;
                    endif
                repeat while(more neighbouring fields?) is (yes);
            repeat while (more diseases?) is (yes)
        endif
    endif
  endif
repeat while (more records?) is (yes)
->no;
stop

@enduml