@startuml Object diagram
object BeingContainer{
    list
    map
}
object Map{
    lenght = 20
    width = 20
    empty 
    table
} 
object Human{
    id = Citizen 1
    represantion = 'm'
    healthPoints = 100
    isInfected = true
    isAlive = true
    sex = male 
    age = 30 
    humanCounter = 2
}
object Doctor{
    id = Citizen 2
    represantion = 'm'
    healthPoints = 100
    isInfected = true
    isAlive = true
    sex = male 
    age = 40 
    humanCounter = 2
}
object EmptySlot{
    id = empty
    representation = ' '
}
object Hospital{
    hospitalNumber = 1
}
object Ambulance{
    capacity = 1
    velocity = 100
    numPassengers = 1
    passengers = //Nie wiem \nco z tą listą 
    numAmb = 1
}
object Hearse{
    capacity = 1
    velocity = 100
    numPassengers = 1
    passengers = //Nie wiem \nco z tą listą
    numHear = 1
}
object Graveyard{
    
}
object Coordinates{
    vertical = 0
    horizontal = 0
}
object Queue{

}
object DiseaseRecord{
    disease = 
    isActive = false 
    infects = false 
    are Symptoms = false 
    isCured = false 
    state = 1
}
object Infector{
    
}
object Virus{
    isActve = false
    timeTilSymptoms = 10
    timeTilInfect = 10
    timeTilCured = 10
    id = Koronaświrus
    infectionRate = 10
    activeRate = 10
    infector = INFECTOR 
    power1 = 10
    power2 = 10
}

Map -o BeingContainer 
Map *-- EmptySlot
Map o-- Human
BeingContainer o-- Human
Map o-- Doctor
BeingContainer o-- Doctor

@enduml 